# Development Override - Hot Reload & Development Tools
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
    volumes:
      - ./backend:/app
      - /app/venv
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
        "--reload-dir",
        "/app",
      ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      # Exclude node_modules and .next to avoid conflicts
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
    stdin_open: true
    tty: true

  # Development tools
  dev-tools:
    image: node:20-alpine
    container_name: reposcope-dev-tools
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: ["tail", "-f", "/dev/null"]
    networks:
      - reposcope-network
