# Pre-commit hooks configuration for RepoScope backend
# https://pre-commit.com/

repos:
  # Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: debug-statements
      - id: check-docstring-first

  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]

  # isort import sorter
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100, --check-only, --diff]

  # flake8 linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=100]
        files: ^backend/.*\.py$
        exclude: ^backend/\.flake8$

  # mypy type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML, fastapi, uvicorn]
        args: [--ignore-missing-imports, --no-strict-optional]

  # Security checks (disabled for now due to configuration issues)
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.10
  #   hooks:
  #     - id: bandit
  #       files: ^backend/.*\.py$
  #       exclude: ^tests/

  # Additional Python checks (disabled for now due to configuration issues)
  # - repo: https://github.com/pycqa/pylint
  #   rev: v3.3.2
  #   hooks:
  #     - id: pylint
  #       args: [--disable=C0114,C0116,R0903,E0401]
  #       exclude: ^tests/
  #       additional_dependencies: [fastapi, uvicorn, pydantic]
  #       files: ^backend/.*\.py$

# Configuration
default_stages: [pre-commit]
fail_fast: false
minimum_pre_commit_version: 4.0.0

# Exclude patterns
exclude: |
  (?x)^(
    \.git/|
    \.venv/|
    venv/|
    \.pytest_cache/|
    __pycache__/|
    \.mypy_cache/|
    build/|
    dist/|
    \.eggs/|
    \.tox/|
    \.coverage/|
    htmlcov/|
    \.cache/|
    \.DS_Store/|
    \.vscode/|
    \.idea/|
    node_modules/|
    \.next/|
    \.nuxt/|
    \.output/|
    \.nitro/|
    \.vercel/|
    \.turbo/
  )
